services:

  # ----- MySQL Service -----
  mysql:
    image: mysql:8.0
    container_name: polybase-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: polyroot
      MYSQL_DATABASE: PolyBase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppolyroot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  # ----- FastAPI Backend Service -----
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polybase-api
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASSWORD: polyroot
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: PolyBase
      HOST: 0.0.0.0
      PORT: 8000

# ----- Persistent Volumes -----
volumes:
  mysql_data:
